# Generated by Django 4.1 on 2022-10-13 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Назва')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disliked_book', models.ManyToManyField(related_name='disliked_book', to='forum.book')),
                ('disliked_descission', models.ManyToManyField(related_name='disliked_descission', to='forum.discussion')),
                ('disliked_discusssion_comment', models.ManyToManyField(related_name='disliked_discusssion_comment', to='forum.discussion_comment')),
                ('last_books', models.ManyToManyField(related_name='last_books', to='forum.book')),
                ('liked_book', models.ManyToManyField(related_name='liked_book', to='forum.book')),
                ('liked_discusion', models.ManyToManyField(related_name='liked_discusion', to='forum.discussion')),
                ('liked_discusssion_comment', models.ManyToManyField(related_name='liked_discusssion_comment', to='forum.discussion_comment')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
