# Generated by Django 4.1 on 2022-10-14 12:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default/default_cover.png', upload_to=user.models.photo_file_name, verbose_name='Обкладинка'),
        ),
    ]
