# Generated by Django 4.1 on 2022-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('user', '0003_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_descission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disliked_discusssion_comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_discusion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_discusssion_comment',
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_discussion',
            field=models.ManyToManyField(related_name='disliked_descission', to='forum.discussion', verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_discussion_comment',
            field=models.ManyToManyField(related_name='disliked_discusssion_comment', to='forum.discussion_comment', verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_discussion',
            field=models.ManyToManyField(related_name='liked_discusion', to='forum.discussion', verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_discussion_comment',
            field=models.ManyToManyField(related_name='liked_discusssion_comment', to='forum.discussion_comment', verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked_book',
            field=models.ManyToManyField(related_name='disliked_book', to='forum.book', verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_books',
            field=models.ManyToManyField(related_name='last_books', to='forum.book', verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_book',
            field=models.ManyToManyField(related_name='liked_book', to='forum.book', verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Назва'),
        ),
    ]
