# Generated by Django 4.1 on 2022-10-15 11:17

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('user', '0004_remove_user_disliked_descission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked_book',
            field=models.ManyToManyField(related_name='disliked_book', to='forum.book', verbose_name='Невподобані книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked_discussion',
            field=models.ManyToManyField(related_name='disliked_descission', to='forum.discussion', verbose_name='Невподобані обговорення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked_discussion_comment',
            field=models.ManyToManyField(related_name='disliked_discusssion_comment', to='forum.discussion_comment', verbose_name='Невподобані коментарі'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Електронна Пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активовано'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Адміністратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_books',
            field=models.ManyToManyField(related_name='last_books', to='forum.book', verbose_name='Останні книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_book',
            field=models.ManyToManyField(related_name='liked_book', to='forum.book', verbose_name='Вподобані книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_discussion',
            field=models.ManyToManyField(related_name='liked_discusion', to='forum.discussion', verbose_name='Вподобані обговорення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_discussion_comment',
            field=models.ManyToManyField(related_name='liked_discusssion_comment', to='forum.discussion_comment', verbose_name='Вподобані коментарі'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default/default_cover.png', upload_to=user.models.photo_file_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Імя'),
        ),
    ]
