# Generated by Django 4.1 on 2022-10-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_created_at_alter_user_disliked_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_discussion_comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_discussion_comment',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активовано'),
        ),
    ]
