# Generated by Django 4.1 on 2022-10-17 13:53

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_book_user_alter_discussion_user_and_more'),
        ('user', '0006_remove_user_disliked_discussion_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_books',
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked_discussion',
            field=models.ManyToManyField(related_name='disliked_discusion', to='forum.discussion', verbose_name='Невподобані обговорення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default/default_avatar.png', upload_to=user.models.photo_file_name, verbose_name='Фото'),
        ),
    ]
