# Generated by Django 4.1 on 2022-10-13 19:10

from django.db import migrations, models
import django.db.models.deletion
import forum.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('search_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000, verbose_name='Опис')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('status', models.CharField(choices=[('OG', 'Виходить'), ('FN', 'Закінчене')], default='OG', max_length=2, verbose_name='Статус')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('cover', models.ImageField(default='default/default_cover.png', upload_to=forum.models.covers_file_name, verbose_name='Обкладинка')),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Book_comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Зміст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Коментар книги',
                'verbose_name_plural': 'Коментарі книги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('search_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000, verbose_name='Опис')),
                ('status', models.CharField(choices=[('OP', 'Відкрите'), ('CL', 'Закрите')], default='OP', max_length=2, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Обговорення',
                'verbose_name_plural': 'Обговорення',
            },
        ),
        migrations.CreateModel(
            name='Discussion_comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Зміст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.discussion_comment')),
            ],
            options={
                'verbose_name': 'Коментар обговорення',
                'verbose_name_plural': 'Коментарі обговорення',
            },
        ),
    ]
