# Generated by Django 4.2.1 on 2023-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
