# Generated by Django 4.1 on 2022-10-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_book_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='New', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='New', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default='New', primary_key=True, serialize=False),
        ),
    ]
