# Generated by Django 4.1 on 2022-10-15 18:45

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_book_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to=forum.models.covers_file_name, verbose_name='Обкладинка'),
        ),
    ]
