# Generated by Django 4.1 on 2022-10-15 20:02

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default/default_cover.jpg', upload_to=forum.models.covers_file_name, verbose_name='Обкладинка'),
        ),
    ]
