# Generated by Django 4.1 on 2022-10-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='discussion_comment',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.discussion_comment'),
        ),
    ]
