# Generated by Django 4.1 on 2022-10-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_discussion_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_comment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='discussion_comment',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.discussion', verbose_name='Обговорення'),
        ),
    ]
