# Generated by Django 4.1 on 2022-10-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_book_comment_book_discussion_comment_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion_comment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.discussion_comment'),
        ),
    ]
