# Generated by Django 4.1 on 2022-10-17 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_discussion_comment_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментар книги', 'verbose_name_plural': 'Коментарі книги'},
        ),
        migrations.AlterModelOptions(
            name='discussion_comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коментар обговорення', 'verbose_name_plural': 'Коментарі обговорення'},
        ),
        migrations.AlterField(
            model_name='book_comment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='forum.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_book', to='forum.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='discussion_comment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.discussion_comment', verbose_name='Відповідь на'),
        ),
        migrations.AlterField(
            model_name='discussion_comment',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='forum.discussion', verbose_name='Обговорення'),
        ),
    ]
